"""init db

Revision ID: 44df277c505d
Revises: 
Create Date: 2025-03-25 16:31:05.435996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44df277c505d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackbronze',
    sa.Column('character_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('realm_name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('bronze_total', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trackbronze')
    # ### end Alembic commands ###
