"""add unique constraint

Revision ID: b05942048977
Revises: 44df277c505d
Create Date: 2025-03-26 15:39:32.159589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b05942048977'
down_revision: Union[str, None] = '44df277c505d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trackbronze', ['character_name', 'realm_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackbronze', type_='unique')
    # ### end Alembic commands ###
